### ISSUE TITLE
Tasks/application/run build issue

### ISSUE THREAD

**Issue by tibbon** [temple2018/Galaxia#28]
I was running everything via the Readme with IntelliJ CE on my Mac. 

```
> Task :run
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3260)
	at java.base/java.lang.Class.getMethod0(Class.java:3246)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at processing.core.PApplet.runSketch(PApplet.java:10707)
	at processing.core.PApplet.main(PApplet.java:10467)
	at org.templegalaxia.GalaxiaGui.main(GalaxiaGui.java:24)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 8 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
3 actionable tasks: 3 executed
Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
6:40:28 PM: Task execution finished 'run'.
```

**Comment by tibbon** [comment]
Similarly:

```java
~/C/Galaxia ❯❯❯ ./gradlew run                                                                                                                                                  ✘ 1 g3-split-petal ✱

> Task :run
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3260)
        at java.base/java.lang.Class.getMethod0(Class.java:3246)
        at java.base/java.lang.Class.getMethod(Class.java:2065)
        at processing.core.PApplet.runSketch(PApplet.java:10707)
        at processing.core.PApplet.main(PApplet.java:10467)
        at org.templegalaxia.GalaxiaGui.main(GalaxiaGui.java:23)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 8 more

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
3 actionable tasks: 1 executed, 2 up-to-date
~/C/Galaxia ❯❯❯                                                                                                                                                                ✘ 1 g3-split-petal ✱
```

**Comment by tibbon** [comment]
I will admit, I rarely/never use Java, so I might be missing something obvious here.

**Comment by Geethree** [comment]
Hey Tibbon. Apologies I wasn't getting notifications from these issues. Does the PR you submitted solve your issue?

**Comment by Geethree** [comment]
It looks like you have `java 10` installed, but you'll need `java 8` to run this bit of software. @meawoppl ?

**Comment by meawoppl** [comment]
No idea!  I suspect there is a way to pin the jdk version, but I don't
think gradle will download that for you...

**Comment by tibbon** [comment]
Looks like my problem was that I had Java / JRE 10 on there, instead of 8/1.8
